version: '3.7'

configs:
  authorized_keys:
    file: 'authorized_keys'

secrets:
  bulwark_database_password:
    external: true
  bulwark_database_root_password:
    external: true
  bulwark_database_config:
    external: true
  bulwark_fedora_config:
    external: true
  bulwark_secrets_config:
    external: true

services:

  redis:
    restart: 'unless-stopped'
    image: 'redis:3.2-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  db:
    restart: 'unless-stopped'
    image: 'mysql:5.7'
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/bulwark_database_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/bulwark_database_root_password
    secrets:
      - bulwark_database_password
      - bulwark_database_root_password
    volumes:
      - 'db:/var/lib/mysql'
  phalt_app:
    image: 'phalt:latest'
    ports:
      - '9292'
    env_file: '.env_phalt'
  web:
    restart: 'unless-stopped'
    depends_on:
      - 'db'
      - 'redis'
    configs:
      - source: 'authorized_keys'
        target: '/home/gitannex/.ssh/authorized_keys'
    image: 'quay.io/upennlibraries/bulwark:latest'
    ports:
      - '80:80'
      - '${SSH_PORT}:22'
    env_file:
      - '.env'
    networks:
      default:
        aliases:
          - 'web'
    secrets:
      - source: bulwark_database_config
        target: /home/app/webapp/config/database.yml
        mode: 0440
      - source: bulwark_fedora_config
        target: /home/app/webapp/config/fedora.yml
        mode: 0440
      - source: bulwark_secrets_config
        target: /home/app/webapp/config/secrets.yml
        mode: 0440
    volumes:
      - 'web:/home/app/webapp'
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - '${PAP_HARVESTING_ENDPOINT_LOCAL}:${PAP_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
      - '${LOCAL_FEATURED}:/home/app/webapp/public/assets/featured'
  sidekiq:
    restart: 'unless-stopped'
    depends_on:
      - 'redis'
    image: 'quay.io/upennlibraries/bulwark:latest'
    ports:
      - '25:25'
    env_file:
      - '.env'
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - '${OPENN_HARVESTING_ENDPOINT_LOCAL}:${OPENN_HARVESTING_ENDPOINT_REMOTE}'
      - '${KAPLAN_HARVESTING_ENDPOINT_LOCAL}:${KAPLAN_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
  rabbitmq:
    restart: 'unless-stopped'
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672'

volumes:
  colenda_workspace:
    external: true
  redis:
  db:
  web:
