version: '3.7'

configs:
  authorized_keys:
    file: authorized_keys

secrets:
  bulwark_database_password:
    external: true
    name: colenda_bulwark_database_password_v${DATABASE_PASSWORD_VERSION}
  bulwark_database_root_password:
    external: true
    name: colenda_bulwark_database_root_password_v${DATABASE_ROOT_PASSWORD_VERSION}
#  bulwark_database_config:
#    external: true
#    name: colenda_bulwark_database_config
  bulwark_honeybadger_api_key:
    external: true
    name: colenda_bulwark_honeybadger_api_key_v${HONEYBADGER_API_KEY_VERSION}
#  bulwark_secrets_config:
#    external: true
#    name: colenda_bulwark_secrets_config

services:
  redis:
    image: 'redis:3.2-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  db:
    image: 'mysql:5.7'
    deploy:
      endpoint_mode: dnsrr
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD_FILE: /run/secrets/bulwark_database_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/bulwark_database_root_password
      MYSQL_USER: ${DATABASE_USERNAME}
    secrets:
      - source: bulwark_database_password
        target: /run/secrets/bulwark_database_password
      - source: bulwark_database_root_password
      - target: /run/secrets/bulwark_database_root_password
#      - bulwark_database_password
#      - bulwark_database_root_password # repeat for root password
    volumes:
      - 'db:/var/lib/mysql'
  phalt_app:
    image: 'gitlab.library.upenn.edu/digital-repository/phalt:${PHALT_IMAGE_TAG}'
    environment:
      IIIF:
      IIIF_BASE:
      OAI_PMH:
      VIRTUAL_HOST:
      VIRTUAL_URL:
      DOWNLOAD_LINK:
      DOWNLOAD_PORT:
      MARMITE_BASE:
      MARMITE_FORMAT:
      STORAGE_HOST:
    ports:
      - '9292'
  web:
    image: 'gitlab.library.upenn.edu/digital-repository/bulwark:${BULWARK_IMAGE_TAG}'
    configs:
      - source: 'authorized_keys'
        target: '/home/gitannex/.ssh/authorized_keys'
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BATCH_OPS_EMAIL:
      CACHE_URL:
      CATALOG_CONTROLLER_PROTOCOL:
      COMBINED_HTTP_LOOKUP:
      DATABASE_NAME:
      DATABASE_USERNAME:
      ERC_DEFAULT_WHO:
      EZID_DEFAULT_SHOULDER:
      EZID_PASSWORD:
      EZID_USER:
      GIT_USER:
      GIT_USER_PASS:
      IIIF_IMAGE_SERVER:
      IMAGING_USER:
      IMAGING_USER_PASS:
      KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE:
      MASTERSRBM_HARVESTING_ENDPOINT_REMOTE:
      MARMITE_URL:
      PAP_HTTP_LOOKUP:
      PAP_STRUCTURAL_HTTP_LOOKUP:
      PHALT_ENDPOINT:
      PROD_FEDORA_PW:
      PROD_FEDORA_URL:
      PROD_FEDORA_USER:
      PROD_SOLR_URL:
      PUBLIC_FEDORA_URL:
      RAILS_ENV:
      REDIS_URL:
      REQUEST_STYLE:
      SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE:
      SCETI_HARVESTING_ENDPOINT_REMOTE:
      KEFFER_HARVESTING_ENDPOINT_REMOTE:
      SMTP_ADDRESS:
      SMTP_DOMAIN:
      SMTP_PORT:
      SPECIAL_REMOTE_NAME:
      STORAGE_ENCRYPTION:
      STORAGE_HOST:
      STORAGE_PORT:
      STORAGE_PROTOCOL:
      STORAGE_PUBLIC:
      STORAGE_READ_HOST:
      STORAGE_READ_PROTOCOL:
      STORAGE_TYPE:
      UV_URL:
      VOYAGER_HTTP_LOOKUP:
      VOYAGER_STRUCTURAL_HTTP_LOOKUP:
    networks:
      default:
        aliases:
          - 'web'
    ports:
      - '80:80'
      - '${SSH_PORT}:22'
    secrets:
      - source: bulwark_database_password
        target: /run/secrets/database_password
      - source: bulwark_honeybadger_api_key
        target: /run/secrets/honeybadger_api_key
      - source: bulwark_secret_key_base
        target: /run/secrets/secret_key_base
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - 'mastersrbm:${MASTERSRBM_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed:${SCETI_COMPLETED_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_2:${SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_3:${SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_4:${SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE}'
      - 'scanstore_rescue:${SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti:${SCETI_HARVESTING_ENDPOINT_REMOTE}'
      - 'keffer:${KEFFER_HARVESTING_ENDPOINT_REMOTE}'
      - 'kaplan_rescue:${KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
      - '${LOCAL_FEATURED}:/home/app/webapp/public/assets/featured'
  sidekiq:
    image: 'gitlab.library.upenn.edu/digital-repository/bulwark:${BULWARK_IMAGE_TAG}'
    command: bash -c "/etc/my_init.d/gitannex.sh && /etc/my_init.d/imaging.sh && /sbin/my_init --skip-startup-files --skip-runit -- bundle exec sidekiq -C config/sidekiq.yml"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      BATCH_OPS_EMAIL:
      CACHE_URL:
      CATALOG_CONTROLLER_PROTOCOL:
      DATABASE_NAME:
      DATABASE_USERNAME:
      ERC_DEFAULT_WHO:
      EZID_DEFAULT_SHOULDER:
      EZID_PASSWORD:
      EZID_USER:
      GIT_USER:
      GIT_USER_PASS:
      IIIF_IMAGE_SERVER:
      IMAGING_USER:
      IMAGING_USER_PASS:
      KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE:
      MASTERSRBM_HARVESTING_ENDPOINT_REMOTE:
      MARMITE_URL:
      PAP_HTTP_LOOKUP:
      PAP_STRUCTURAL_HTTP_LOOKUP:
      PHALT_ENDPOINT:
      PROD_FEDORA_PW:
      PROD_FEDORA_URL:
      PROD_FEDORA_USER:
      PROD_SOLR_URL:
      PUBLIC_FEDORA_URL:
      RAILS_ENV:
      REDIS_URL:
      REQUEST_STYLE:
      SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE:
      SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE:
      SCETI_HARVESTING_ENDPOINT_REMOTE:
      KEFFER_HARVESTING_ENDPOINT_REMOTE:
      SMTP_ADDRESS:
      SMTP_DOMAIN:
      SMTP_PORT:
      SPECIAL_REMOTE_NAME:
      STORAGE_ENCRYPTION:
      STORAGE_HOST:
      STORAGE_PORT:
      STORAGE_PROTOCOL:
      STORAGE_PUBLIC:
      STORAGE_READ_HOST:
      STORAGE_READ_PROTOCOL:
      STORAGE_TYPE:
      VOYAGER_HTTP_LOOKUP:
      VOYAGER_STRUCTURAL_HTTP_LOOKUP:
    secrets:
      - source: bulwark_database_password
        target: /run/secrets/database_password
      - source: bulwark_honeybadger_api_key
        target: /run/secrets/honeybadger_api_key
      - source: bulwark_secret_key_base
        target: /run/secrets/secret_key_base
    volumes:
      - '${LOCAL_DATA}:${REMOTE_DATA}'
      - 'mastersrbm:${MASTERSRBM_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed:${SCETI_COMPLETED_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_2:${SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_3:${SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti_completed_4:${SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE}'
      - 'sceti:${SCETI_HARVESTING_ENDPOINT_REMOTE}'
      - 'keffer:${KEFFER_HARVESTING_ENDPOINT_REMOTE}'
      - 'scanstore_rescue:${SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'kaplan_rescue:${KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE}'
      - 'colenda_workspace:${REMOTE_WORKSPACE}'
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672'

volumes:
  colenda_workspace:
    external: true
  mastersrbm:
    external: true
  sceti_completed:
    external: true
  sceti_completed_2:
    external: true
  sceti_completed_3:
    external: true
  sceti_completed_4:
    external: true
  sceti:
    external: true
  keffer:
    external: true
  scanstore_rescue:
    external: true
  kaplan_rescue:
    external: true
  redis:
  db:
