version: '2'

services:

  redis:
    image: 'redis:3.2-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  db:
    image: 'mysql/mysql-server:5.7'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    ports:
      - '80:80'
    env_file:
      - '.env'
    links:
      - db
    volumes:
      - 'web:/home/app/webapp'
  sidekiq:
    depends_on:
      - 'redis'
    build: .
    links:
      - 'redis'
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - '.:/webapp'
    env_file:
      - '.env'

volumes:
  redis:
  db:
  web:




