version: '2'

services:

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  web:
    depends_on:
      - 'redis'
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    links:
      - db
    volumes:
      - "/webapp:/home/app/webapp"
  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/webapp'
    env_file:
      - '.env'

volumes:
  redis:
