development:
  email: <%= ENV['BATCH_OPS_EMAIL'] %>
test:
  email: <%= ENV['BATCH_OPS_EMAIL'] %>

deployed: &deployed
  email: <%= ENV['BATCH_OPS_EMAIL'] %>
bulwark_dev: *deployed
bulwark_test: *deployed
bulwark_production: *deployed