development:
  adapter: solr
  url: http://localhost:8983/solr/blacklight-core
test: &test
  adapter: solr
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/test" %>
production:
  adapter: solr
  url: <%= ENV['PROD_SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
