development:
  mounted_drives:
    test: <%= Rails.root.join('spec', 'fixtures', 'example_bulk_imports') %>
  marmite:
    url: http://marmite.library.upenn.edu:9292
  bulk_import:
    create_iiif_manifest: false

test:
  mounted_drives:
    test: <%= Rails.root.join('spec', 'fixtures', 'example_bulk_imports') %>
  marmite:
    url: https://marmite.library.upenn.edu:9292
  bulk_import:
    create_iiif_manifest: false

production:
  mounted_drives:
    kaplan-rescue: <%= ENV['KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE'] %>
    scanstore-rescue: <%= ENV['SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed-2: <%= ENV['SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed-3: <%= ENV['SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed-4: <%= ENV['SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE'] %>
    oceanus-sceti: <%= ENV['OCEANUS_SCETI_HARVESTING_ENDPOINT_REMOTE'] %>
    mastersrbm:  <%= ENV['MASTERSRBM_HARVESTING_ENDPOINT_REMOTE'] %>
  marmite:
    url: <%= ENV['MARMITE_URL'] %>
  bulk_import:
    create_iiif_manifest: true
