default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bulwark_development
  host: 127.0.0.1
  username: root
  password:
  port: 3307

test:
  <<: *default
  database: bulwark_test
  host: 127.0.0.1
  username: root
  password:
  port: 3307

deployed: &deployed
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: db
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= File.exist?('/run/secrets/database_password') ? File.read('/run/secrets/database_password').strip : ENV['DATABASE_PASSWORD'] %>

bulwark_dev: *deployed
bulwark_test: *deployed
bulwark_production: *deployed