# Display mechanisms settings

development:
  iiif:
    image_server: <%= ENV['IIIF_IMAGE_SERVER'] %>

test:
  iiif:
    image_server: <%= ENV['IIIF_IMAGE_SERVER'] %>

deployed: &deployed
  iiif:
    image_server: <%= ENV['IIIF_IMAGE_SERVER'] %>

bulwark_dev: *deployed
bulwark_test: *deployed
bulwark_production: *deployed