development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora/rest
  base_path: /test
production:
  user: <%= ENV["PROD_FEDORA_USER"] %>
  password: <%= ENV["PROD_FEDORA_PW"] %>
  url: <%= ENV["PROD_FEDORA_URL"] %>
  base_path: /prod
