# Config file for defining allowed/restricted file types

development:
  allowed_extensions:
    assets: 'tif,tiff,jpeg,jpg,wav,mp3,mp4,zip,gz,pdf'
    metadata_sources: 'xlsx,csv'

test:
  allowed_extensions:
    assets: "comma,separated,file,extensions"
    metadata_sources: "comma,separated,file,extensions"

deployed: &deployed
  allowed_extensions:
    assets: 'tif,tiff,jpeg,jpg,wav,mp3,mp4,zip,gz,pdf'
    metadata_sources: 'xlsx,csv'

bulwark_dev: *deployed
bulwark_test: *deployed
bulwark_production: *deployed