# Config file for working with the filesystem

development:
  manifest_location: /path/to/manifest.txt
  fedora_xml_derivative: fedora.xml
  mets_xml_derivative: mets.xml
  object_admin_path: .repoadmin
  object_derivatives_path: .derivs
  object_semantics_location: fs_semantics
  remote_repo_permissions: =rx,ug+rwx
  init_script_path: /path/to/init.sh
  init_script_permissions: a+x
  object_data_path: data
  workspace: /path/to/scratch
  assets_path: /path/to/colenda_dirs/fs/pub/data
  assets_display_path: /path/to/colenda_dirs/fs/pub/display
  metadata_path_label: METADATA_PATH
  file_path_label: ASSETS_PATH
  repository_prefix: UPENNLIB
  supported_vca_version: 6
  input_source_prefix: input_source
  problem_log: problems_log
test:
  manifest_location: /path/to/manifest.txt
  metadata_path_label: metadata_label_in_manifest
  file_path_label: file_path_label_in_manifest
  repository_prefix: prefix
production:
  manifest_location: /home/app/webapp/docker/manifest.txt
  fedora_xml_derivative: fedora.xml
  mets_xml_derivative: mets.xml
  object_admin_path: .repoadmin
  object_derivatives_path: .derivs
  object_semantics_location: fs_semantics
  remote_repo_permissions: =rx,ug+rwx
  init_script_path: /home/app/webapp/docker/init.sh
  init_script_permissions: a+x
  object_data_path: data
  workspace: /fs/priv/workspace
  assets_path: /fs/pub/data
  assets_display_path: /fs/pub/display
  metadata_path_label: METADATA_PATH
  file_path_label: ASSETS_PATH
  repository_prefix: UPENNLIB
  supported_vca_version: 6
  input_source_prefix: input_source
  problem_log: problems_log
