default:
  startup_wait: 90
  jetty_port: 8983
  java_opts:
    - "-Xmx512m"
    - "-XX:MaxPermSize=128m"
    - "-Dfcrepo.modeshape.configuration=file:///Users/katherly/Documents/Rails/head/config/repository.json"

