development:
  log_name:
    checksum: "checksums.tsv"
test:
  log_name:
    checksum: "checksums.tsv"
deployed: &deployed
  log_name:
    checksum: "checksums.tsv"
bulwark_dev: *deployed
bulwark_test: *deployed
bulwark_production: *deployed