development:
  root_element_options:
    - records
    - record
    - pages
    - page
  parent_element_options:
    - record
    - page
    - image
  schema_terms:
    - abstract
    - contributor
    - coverage
    - creator
    - date
    - description
    - format
    - identifier
    - includes
    - includesComponent
    - language
    - publisher
    - relation
    - rights
    - source
    - subject
    - title
    - type
    - file_name
    - page_number
    - ocr_text
    - parent_manuscript
    - exhibit_id
  canonical_identifier_path:
    - /root/record/uuid
  unique_identifier_field: uuid
  erc:
    default_who: <%= ENV['ERC_DEFAULT_WHO'] %>
  voyager:
    root_element: record
    http_lookup: <%= ENV['VOYAGER_HTTP_LOOKUP'] %>
    structural_http_lookup: <%= ENV['VOYAGER_STRUCTURAL_HTTP_LOOKUP'] %>
    structural_identifier_prefix: MEDREN_
    multivalue_fields:
      - abstract
      - contributor
      - coverage
      - creator
      - date
      - description
      - identifier
      - includes
      - includesComponent
      - language
      - publisher
      - relation
      - rights
      - source
      - subject
      - title
      - type
      - collection
      - personal_name
      - corporate_name
      - geographic_subject
      - provenance
  pap:
    http_lookup:  <%= ENV['PAP_HTTP_LOOKUP'] %>
    http_lookup_suffix: show?format=marc21
    structural_http_lookup: <%= ENV['PAP_STRUCTURAL_HTTP_LOOKUP'] %>
    structural_lookup_suffix: show?format=structural
  pqc_ark:
    structural_http_lookup: <%= ENV['PAP_STRUCTURAL_HTTP_LOOKUP'] %>
    structural_lookup_suffix: show?format=structural_ark
  combined:
    http_lookup: <%= ENV['COMBINED_HTTP_LOOKUP'] %>
    http_lookup_suffix: show?format=combined_ark
  ead_xml:
    root_element: record
test:
  root_element_options:
    - record
    - page
  parent_element_options:
    - pages
    - records
  schema_terms:
    - title
    - author
  canonical_identifier_path:
    - identifier
  unique_identifier_field: identifier
  voyager:
    root_element: root
    http_lookup: <%= ENV['VOYAGER_HTTP_LOOKUP_URL'] %>
    structural_http_lookup: <%= ENV['VOYAGER_HTTP_LOOKUP_URL'] %>
    structural_identifier_prefix:
    multivalue_fields:
      - language
      - subject
production:
  root_element_options:
    - records
    - record
    - pages
    - page
  parent_element_options:
    - record
    - page
    - image
  schema_terms:
    - identifier
    - abstract
    - coverage
    - description
    - language
    - date
    - title
    - creator
    - file_name
    - page_number
    - ocr_text
    - parent_manuscript
    - exhibit_id
  canonical_identifier_path:
    - /root/record/uuid
  unique_identifier_field: uuid
  erc:
    default_who: <%= ENV['ERC_DEFAULT_WHO'] %>
  voyager:
    root_element: record
    http_lookup: <%= ENV['VOYAGER_HTTP_LOOKUP'] %>
    structural_http_lookup: <%= ENV['VOYAGER_STRUCTURAL_HTTP_LOOKUP'] %>
    structural_identifier_prefix: MEDREN_
    multivalue_fields:
      - abstract
      - contributor
      - coverage
      - creator
      - date
      - description
      - identifier
      - includes
      - includesComponent
      - language
      - publisher
      - relation
      - rights
      - source
      - subject
      - title
      - type
      - collection
      - personal_name
      - corporate_name
      - geographic_subject
      - provenance
  pap:
    http_lookup: <%= ENV['PAP_HTTP_LOOKUP'] %>
    http_lookup_suffix: create?format=marc21
    structural_http_lookup: <%= ENV['PAP_STRUCTURAL_HTTP_LOOKUP'] %>
    structural_lookup_suffix: create?format=structural
  pqc_ark:
    structural_http_lookup: <%= ENV['PAP_STRUCTURAL_HTTP_LOOKUP'] %>
    structural_lookup_suffix: show?format=structural_ark
  combined:
    http_lookup: <%= ENV['COMBINED_HTTP_LOOKUP'] %>
    http_lookup_suffix: show?format=combined_ark
