development:
  root_element_options:
    - records
    - record
    - pages
    - page
  parent_element_options:
    - record
    - page
    - image
  schema_terms:
    - identifier
    - abstract
    - coverage
    - description
    - language
    - date
    - title
    - author
    - file_name
    - page_number
    - ocr_text
    - parent_manuscript
  canonical_identifier_path:
    - /root/record/identifier
  voyager:
    root_element: record
    http_lookup: http://dla.library.upenn.edu/dla/franklin/lookup
    multivalue_fields:
      - coverage
      - language
      - subject
test:
  root_element_options:
    - record
    - page
  parent_element_options:
    - pages
    - records
  schema_terms:
    - title
    - author
  canonical_identifier_path:
    - /root/record/identifier
  voyager:
    root_element: root
    http_lookup: http://url/to/http/no/trailing/slash
    multivalue_fields:
      - language
      - subject
production:
  root_element_options:
    - record
    - page
  parent_element_options:
    - pages
    - records
  schema_terms:
    - title
    - author
  canonical_identifier_path:
    - /root/record/identifier
  voyager:
    root_element: root
    http_lookup: http://url/to/http/no/trailing/slash
    multivalue_fields:
      - language
      - subject
