:concurrency: 1
:logfile: ./log/sidekiq.log
:queues:
  - [file_checks, 1]
  - [ingest, 1]
  - [validate_manifest, 1]
  - [create_repos, 1]
  - [process_manifest, 1]
  - [process_batch, 1]
  - [maintenance, 1]
  - [xml, 1]
  - [metadata_extraction, 1]
:max_retries: 0
