:concurrency: 1
:logfile: ./log/sidekiq.log
:queues:
  - high
  - medium
  - file_checks
  - ingest
  - validate_manifest
  - create_repos
  - process_manifest
  - process_batch
  - maintenance
  - xml
  - metadata_extraction
  - low
:max_retries: 0
