# This is a sample config file that points to a solr server for each environment
development:
  url: http://bulwark.solr.lndo.site/solr/bulwark-development
test:
  url: http://bulwark.solr.lndo.site/solr/bulwark-test
deployed: &deployed
  url: <%= ENV['SOLR_URL']%>
bulwark_dev: *deployed
bulwark_test: *deployed
bulwark_production: *deployed